<a href="https://colab.research.google.com/github/alifele/Machine_learning/blob/master/Machine_learning/Little_functions%26Little_Tricks/Loading_data_from_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here is another way to upload data from github in colab by cloning github

# An example which was on web

In [1]:
!pip install -q xlrd
!git clone https://github.com/fastai/courses.git

Cloning into 'courses'...
remote: Enumerating objects: 765, done.
remote: Total 765 (delta 0), reused 0 (delta 0), pack-reused 765
Receiving objects: 100% (765/765), 23.06 MiB | 28.28 MiB/s, done.
Resolving deltas: 100% (407/407), done.

In [2]:
!ls courses/deeplearning1/excel

collab_filter.xlsx  entropy_example.xlsx  layers_example.xlsx
conv-example.xlsx   graddesc.xlsm

In [3]:
import pandas as pd
df = pd.read_excel('courses/deeplearning1/excel/layers_example.xlsx')
df

,Unnamed: 0,x1,x2,x3,Unnamed: 4,Unnamed: 5,y1,y2,Unnamed: 8,Unnamed: 9
0,NaN,2,3.000000,1.000000,NaN,NaN,0,1.000000,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,weights 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1.77752,-0.056013,0.222363,-0.125313,NaN,NaN,NaN,NaN,0.666667
4,NaN,0.58263,-0.153056,0.122250,0.597437,NaN,NaN,NaN,NaN,NaN
5,NaN,0.385083,0.402703,0.107784,-1.325171,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,activations 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,5.68802,-0.168491,0.919260,0.216514,NaN,NaN,NaN,NaN,NaN
9,NaN,5.68802,0.000000,0.919260,0.216514,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,weights 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,-1.01076,0.470262,0.246334,NaN,NaN,NaN,NaN,NaN,0.500000
13,NaN,-0.659433,-0.161928,0.218346,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,0.119704,0.521594,-0.372220,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,-0.463218,-0.155967,0.114281,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,activations 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,-5.7395,3.120573,1.083727,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,0,3.120573,1.083727,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,weights output,NaN,NaN,NaN,NaN,dl/dw,NaN,NaN,NaN
22,NaN,0.914665,0.612213,NaN,NaN,NaN,0.0880227,-0.058916,NaN,0.666667
23,NaN,0.372557,1.240222,NaN,NaN,NaN,0.035853,-0.119353,NaN,NaN
24,NaN,-0.333152,-0.764842,NaN,NaN,NaN,-0.0320609,0.073605,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,activations output,NaN,NaN,NaN,NaN,dl/dout,NaN,NaN,NaN
27,NaN,0.801546,3.041323,NaN,NaN,NaN,0.0962349,-0.096235,NaN,NaN
28,NaN,softmax,NaN,23.161911,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,0.0962349,0.903765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,rmse,0.136097,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# My example
here is my code which I uploaded data from my repository

In [4]:
!pip install -q xlrd
!git clone https://github.com/alifele/Neuro_Science.git

fatal: destination path 'Neuro_Science' already exists and is not an empty directory.

In [5]:
!ls Neuro_Science

Data.npy		Neuro_PCA.ipynb
DataSet_with_Label.npz	README.md
IF_data.npz		Techniques_with_Bias_and_Variance.ipynb

In [0]:
import numpy as np
data = np.load('Neuro_Science/DataSet_with_Label.npz')  # note that in address you should not write your github page name